

networks:
  dams-internal-network:
    driver: bridge
  dams-external-network:
    driver: bridge

volumes:
  dams-postgres-data:

services:
  dams-postgres:
    image: postgres:latest
    container_name: dams-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dams-postgres-data:/var/lib/postgresql/data
    networks:
      - dams-internal-network

  dams-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    # image: ghcr.io/tharattt/dams-server:latest
    container_name: dams-server
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: dams-postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_DIALECT: ${DB_DIALECT}
      JWT_TOKEN: ${JWT_TOKEN}
      PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - dams-postgres
    networks:
      - dams-internal-network
      - dams-external-network

  dams-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: dams-client
    restart: always
    environment:
      CLIENT_HOST: "0.0.0.0"
      CLIENT_PORT: ${CLIENT_PORT}
      SERVER_HOST: "dams-server"
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - dams-server
    networks:
      - dams-external-network
