---


- name: Download docker compose from S3
  aws_s3:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_object }}"
    dest: "{{ docker_compose_path }}"
    overwrite: always
    mode: get
  register: download_compose
  when: s3_bucket is defined and s3_object is defined and docker_compose_path is defined

- name: Download .env from s3
  aws_s3:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_object_env }}"
    dest: "{{ env_path }}"
    overwrite: always
    mode: get
  register: download_env
  when: s3_bucket is defined and s3_object_env is defined and env_path is defined

- name: Run docker compose down
  command: docker compose -f {{ docker_compose_path }} down
  register: compose_down
  when: download_compose.changed or download_env.changed
  args:
    chdir: "{{ docker_compose_path | dirname }}"

- name: Run docker compose pull
  command: docker compose -f {{ docker_compose_path }} pull
  register: compose_pull
  when: download_compose.changed or download_env.changed
  args:
    chdir: "{{ docker_compose_path | dirname }}"

- name: Run docker compose up
  command: docker compose -f {{ docker_compose_path }} up -d --remove-orphans
  register: compose_up
  when: download_compose.changed or download_env.changed
  args:
    chdir: "{{ docker_compose_path | dirname }}"
