---

- name: Install docker
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install docker and dependencies
      include_tasks: roles/install-docker/tasks/main.yml

- name: Deploy project
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Run docker compose
      include_tasks: roles/run-docker-compose/tasks/main.yml
      vars:
        s3_bucket: "{{ lookup('env', 'S3_BUCKET') }}"
        s3_object: "{{ lookup('env', 'S3_OBJECT') }}"
        s3_object_env: "{{ lookup('env', 'S3_OBJECT_ENV') }}"
        docker_compose_path: "{{ lookup('env', 'DOCKER_COMPOSE_PATH') }}"
        env_path: "{{ lookup('env', 'ENV_PATH') }}"