name: Deploy Project to AWS EC2

on:
  workflow_dispatch:
  workflow_call:

jobs:
  add-docker-compose-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Upload docker-compose.yml and .env to S3
        run: |
          aws s3 cp docker-compose-prod.yml s3://${{ secrets.S3_BUCKET }}/${{ secrets.S3_OBJECT }}
          aws s3 cp .env s3://${{ secrets.S3_BUCKET }}/${{ secrets.S3_OBJECT_ENV }}

  deploy-project:
    needs: add-docker-compose-to-s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible playbook to deploy project
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_OBJECT: ${{ secrets.S3_OBJECT }}
          S3_OBJECT_ENV: ${{ secrets.S3_OBJECT_ENV }}
          DOCKER_COMPOSE_PATH: /home/ubuntu/docker-compose.yml
          ENV_PATH: /home/ubuntu/.env
        run: |
          ansible-playbook ansible/deploy-project.yml \
          -i ${{ secrets.ANSIBLE_HOST_IP}}, --extra-vars "ansible_user=${{ secrets.ANSIBLE_USER }}" \
          --extra-vars"ansible_ssh_private_key_file=${{ secrets.ANSIBLE_SSH_PRIVATE_KEY_FILE }}" \
          --private-key ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY_FILE }} \
          --user ${{ secrets.ANSIBLE_USER }}  --extra-vars "s3_bucket=${{ secrets.S3_BUCKET }}" \
          --extra-vars "s3_object=${{ secrets.S3_OBJECT }}" \
          --extra-vars "s3_object_env=${{ secrets.S3_OBJECT_ENV }}" \
          --extra-vars "docker_compose_path=/home/ubuntu/docker-compose.yml" \
          --extra-vars "env_path=/home/ubuntu/.env"