name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: your_database_name
          MYSQL_USER: your_database_user
          MYSQL_PASSWORD: your_database_password
        ports:
          - 3306:3306

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub (optional, if pushing images to Docker Hub)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push backend Docker image
    - name: Build and push backend image
      run: |
        docker build -t your-dockerhub-username/backend ./server
        docker push your-dockerhub-username/backend

    # Build and push frontend Docker image
    - name: Build and push frontend image
      run: |
        docker build -t your-dockerhub-username/frontend ./client
        docker push your-dockerhub-username/frontend

    # Deploy (optional, if deploying to AWS or another platform)
    - name: Deploy to AWS (example)
      run: |
        echo "Deploying to AWS..."
        # Add your deployment commands here