name: Run SonarCloud Scan

on:
  workflow_call:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Artifacts
      uses: actions/download-artifact@v4

    - name: Run SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectKey: ParvathyUllas25
        organization: parvathyullas25
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
